Fix evil-ex-search-backward stuck on first match
emacs-evil/evil pull request #1436
Opened 2021-03-16 23:25 UTC by Abdillah

Fixes #1435

2021-03-18 22:46 UTC, tomdl89 requested changes

2021-03-18 22:46 UTC, tomdl89 commented on evil-search.el
> +                     (- evil-ex-search-start-point 1)))
To be consistent with the line above:
```suggestion
                     (1- evil-ex-search-start-point)))
```

2021-03-18 22:49 UTC, tomdl89 commented
Well spotted. I think most people would never find this, because we'd use `evil-ex-search-next` instead of running `evil-ex-search-backward` again. Out of interest, why are you doing it like this?

2021-03-19 00:28 UTC, Abdillah commented
> why are you doing it like this?

Well, I was just looking for `forward` and `backward` search functionality and both pop up in suggestion.

2021-03-19 00:29 UTC, Abdillah commented on evil-search.el
> +                     (- evil-ex-search-start-point 1)))
Okay, wait a moment

2021-03-19 15:38 UTC, tomdl89 commented
The usual way to repeat the same search in the same direction is to press `n`. If you're using `evil-search` you may want to rebind `n` and `N` to `evil-ex-search-next` and `evil-ex-search-previous` respectively.

2021-03-19 15:39 UTC, merged